# Generated by Django 6.0.1 on 2026-01-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
