# Generated by Django 6.0.1 on 2026-01-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_favorit'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='stok',
            field=models.IntegerField(default=1),
        ),
    ]
